### ISSUE TITLE
网页字体不太整齐

### ISSUE THREAD

**Issue by Prurite** [Strontium233/onegraphwebapp#1]
建议改成 Consolas 等整齐一些的字体。（强迫症

**Comment by Strontium233** [comment]
谢谢反馈
没想到字体被这么多人吐槽……我还挺喜欢这个字体的
会在下次release修改

**Comment by Strontium233** [comment]
[https://github.com/Strontium233/onegraphwebapp/commit/d73c234337cfdb68876fb85c8457c016a7366013](url) fixed this

**Comment by Strontium233** [comment]
commit d73c234 fixed this
