### ISSUE TITLE
表格排版比较混乱

### ISSUE THREAD

**Issue by Ruby280255768** [Strontium233/onegraphwebapp#2]
可以使用`<table></table>`来排版吗，效果图如下，代码不太会写。
![1](https://user-images.githubusercontent.com/18400004/73769876-686fd180-47b6-11ea-926b-db1680317f98.png)
自己瞎写的表格代码如下：
[test.txt](https://github.com/Strontium233/onegraphwebapp/files/4154941/test.txt)

**Comment by Strontium233** [comment]
你好
<table>的话是可以的
一开始考虑的是散排，没考虑使用表格layout
会在下次release修正
